config/routes.rb
Rails.application.routes.draw do
  
  resources :feeds
  resources :jibsas
  root 'posts#index'
  # root 'jibsas#index'
  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"
  
  devise_for :users
  resources :categories
  resources :posts
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/posts/hashtag/:name', to:'posts#hashtags'
  get '/jibsas/jhashtag/:name', to:'jibsas#hashtags'

  get '/404' , to: 'errors#not_found'
  get '/422' , to: 'errors#unacceptable'
  get '/500' , to: 'errors#server_errors'

  get 'hubs/seed_files'
  get 'hubs/about_us'
  get 'hubs/error_test'
  get 'hubs/popular'
  get 'hubs/random_view'
  get 'hubs/new_index'
  get 'hubs/popular_today'
  get 'hubs/dry_feed'
  get 'hubs/wet_feed'
  get 'hubs/nutrition_dic'
  get 'hubs/for_catfeed_store'
  get 'hubs/testing'
  get 'hubs/product_comparison'
  
  

  # Feed_detail
  get 'feed_detail/fd_01'
end

app/models/jibsa.rb
class Jibsa < ApplicationRecord
  has_rich_text :j_description
  has_rich_text :j_spare_31

  acts_as_punchable
  
  belongs_to :user
  has_and_belongs_to_many :tags

  extend FriendlyId
  friendly_id :j_friendly_id, use: :slugged

  after_create do
    jibsa = Jibsa.find_by(id: self.id)
    jhashtags = self.j_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    jhashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        jibsa.tags << tag
    end
  end
  
  before_update do
    jibsa = Jibsa.find_by(id: self.id)
    jibsa.tags.clear
    jhashtags = self.j_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    jhashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        jibsa.tags << tag
    end
  end

  def self.search_by(search_term)
    where("LOWER(j_title) LIKE :search_term OR LOWER(j_hashtag) LIKE :search_term", search_term: "%#{search_term.downcase}%")
  end 
  
end

app/controllers/jibsas_controller.rb
class JibsasController < ApplicationController
  before_action :set_jibsa, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index, :hashtags]

  # GET /jibsas or /jibsas.json
  def index
    @pagy, @jibsas = pagy(Jibsa.all.order("created_at DESC"), items: 10)
    @latest_feeds = Feed.last(1)
    @except_first_feeds = Feed.order("id desc").offset(1).all
    ### Blog에 사용할것
    # @latest_post = Jibsa.last(1) #마지막 포스팅만 보여준다
    # @except_first_posts = Jibsa.order("id desc").offset(1).all #마지막 포스팅만 뺴고 보여준다
    

    if params[:search]
      @search_term = params[:search]
      @jibsas = @jibsas.search_by(@search_term)
    end
  end

  # GET /jibsas/1 or /jibsas/1.json
  def show
    @jibsa.punch(request)
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @pagy, @jibsas = pagy(tag.jibsas.order("created_at DESC"), items: 20)
  end

  # GET /jibsas/new
  def new
    @jibsa = Jibsa.new
  end

  # GET /jibsas/1/edit
  def edit
  end

  # POST /jibsas or /jibsas.json
  def create
    @jibsa = Jibsa.new(jibsa_params)
    @jibsa.user = current_user
    respond_to do |format|
      if @jibsa.save
        format.html { redirect_to @jibsa, notice: "Jibsa was successfully created." }
        format.json { render :show, status: :created, location: @jibsa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @jibsa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jibsas/1 or /jibsas/1.json
  def update
    respond_to do |format|
      if @jibsa.update(jibsa_params)
        format.html { redirect_to @jibsa, notice: "Jibsa was successfully updated." }
        format.json { render :show, status: :ok, location: @jibsa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @jibsa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jibsas/1 or /jibsas/1.json
  def destroy
    @jibsa.destroy
    respond_to do |format|
      format.html { redirect_to jibsas_url, notice: "Jibsa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jibsa
      @jibsa = Jibsa.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def jibsa_params
      params.require(:jibsa).permit(:j_title, :j_link, :j_image, :j_source, :j_hashtag, :j_rating, :j_review_count, :j_key_word, 
                                    :j_link, :j_is_price, :j_was_price, :j_pct, :j_friendly_id, :j_spare_56, :j_option_01, :j_option_02, :j_option_03,
                                    :j_option_04, :j_option_05, :j_option_06, :j_option_07, :j_spare_01, :j_spare_02, :j_spare_03, :j_spare_04, :j_spare_05,
                                    :j_spare_06, :j_spare_07, :j_spare_08, :j_spare_09, :j_spare_10, :j_spare_31, :j_spare_32, :j_option_11, :j_option_12 , :j_option_13,
                                    :j_option_14, :j_option_15, :j_option_16, :j_option_17, :j_option_18, :j_option_19, :j_description, :j_string_01, :j_string_02, :j_string_03,
                                    :j_string_04, :j_string_05, :j_text_01, :j_text_02, :j_text_03, :j_text_04, :j_text_05, :j_text_06, :j_text_07)
    end
end

app/helpers/jibsas_helper.rb
module JibsasHelper
  def render_with_jhashtags(j_hashtag)
    j_hashtag.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/jibsas/jhashtag/#{word.delete('#')}"}.html_safe
  end 
end

app/views/jibsas/_blog_section.html.erb
<div class="blog_wrap clearfix">

  <div class="blog_box clearfix">
    <h2>사료</h2>

    <% @latest_feeds.each do |feed| %>
      <div class="blog_hero">
        <a href="#n"><img src="<%= feed.f_image %>" alt="<%= feed.f_title %>"></a>
        <div class="inner">
          <h3><%= feed.f_title %></h3>
          <span>UPDATED DECEMBER 16, 2021</span>
          <p><%= feed.f_description %></p>
        </div>
        <!-- <div class="more"><a href="/feeds/<%= feed.id %>">더 읽기</a></div> -->
        <div class="more"><a href="#n">더 읽기</a></div> <!-- a tag 주소는 컨텐츠 페이지로 연결하기 -->
        <span><%= link_to 'Edit', edit_feed_path(feed) %></span>
        <span><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      </div>
    <% end %>

    <div class="blog_sub clearfix">

      <% @except_first_feeds.each do |feed| %>
        <a href="#n">
          <div class="blog_card clearfix">
            <div class="img_box">
              <img src="<%= feed.f_image %>" alt="<%= feed.f_title %>">
            </div>
            <div class="inner">
              <h3><%= feed.f_title %></h3>
              <span>UPDATED DECEMBER 16, 2021</span>
            </div>
            <div class="sub_more"><a href="#n">더 읽기</a></div>
            <span><%= link_to 'Edit', edit_feed_path(feed) %></span>
          <span><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          </div>

        </a>
      <% end %>

      <div class="blog_card clearfix">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="">
        </div>
        <div class="inner">
          <h3>Title</h3>
          <span>UPDATED DECEMBER 16, 2021</span>
        </div>
      </div>

      <div class="blog_card clearfix">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="">
        </div>
        <div class="inner">
          <h3>Title</h3>
          <span>UPDATED DECEMBER 16, 2021</span>
        </div>
      </div>

    </div>

  </div><!-- blog_box -->

  <div class="blog_box clearfix">
    <h2>사료</h2>

    <div class="blog_hero">
      <img src="https://images.unsplash.com/photo-1494256997604-768d1f608cac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=929&q=80" alt="">
      <div class="inner">
        <h3>고양이 사료 고르는 방법</h3>
        <span>UPDATED DECEMBER 16, 2021</span>
        <p>불러 광야에서 그들의 많이 끓는 뿐이다. 영락과 끓는 인간의 석가는 힘차게 것이다. 청춘에서만 이것을 것은 위하여 붙잡아 뿐이다. 뛰노는 가슴이 사랑의 간에 그들에게 대한 역사를 끓는 얼마나 말이다. 이상 따뜻한 동산에는 눈이 예수는 얼마나 청춘을 보배를 있으랴?</p>
      </div>
    </div>

    <div class="blog_sub clearfix">

      <div class="blog_card clearfix">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="">
        </div>
        <div class="inner">
          <h3>Title</h3>
          <span>UPDATED DECEMBER 16, 2021</span>
        </div>
      </div>

      <div class="blog_card clearfix">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="">
        </div>
        <div class="inner">
          <h3>Title</h3>
          <span>UPDATED DECEMBER 16, 2021</span>
        </div>
      </div>

      <div class="blog_card clearfix">
        <div class="img_box">
          <img src="https://images.unsplash.com/photo-1529778873920-4da4926a72c2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="">
        </div>
        <div class="inner">
          <h3>Title</h3>
          <span>UPDATED DECEMBER 16, 2021</span>
        </div>
      </div>

    </div>

  </div><!-- blog_box -->

</div><!-- blog_wrap -->

app/views/jibsas/_codes_brand.html.erb
<% if @jibsa.j_option_06 == 801 %>
  <em>로얄캐닌</em>
<% elsif @jibsa.j_option_06 == 802 %>
  <em>캐츠랑</em>
<% elsif @jibsa.j_option_06 == 803 %>
  <em>ANF</em>
<% elsif @jibsa.j_option_06 == 804 %>
  <em>뉴트리나</em>
<% elsif @jibsa.j_option_06 == 805 %>
  <em>이즈칸</em>
<% elsif @jibsa.j_option_06 == 806 %>
  <em>네츄럴코어</em>
<% elsif @jibsa.j_option_06 == 807 %>
  <em>위스카스</em>
<% elsif @jibsa.j_option_06 == 808 %>
  <em>퓨리나</em>
<% elsif @jibsa.j_option_06 == 809 %>
  <em>프로베스트</em>
<% elsif @jibsa.j_option_06 == 810 %>
  <em>오리젠</em>
<% elsif @jibsa.j_option_06 == 811 %>
  <em>네추럴밸런스</em>
<% elsif @jibsa.j_option_06 == 812 %>
  <em>나우프레쉬</em>
<% elsif @jibsa.j_option_06 == 813 %>
  <em>대한사료</em>
<% elsif @jibsa.j_option_06 == 814 %>
  <em>웰츠</em>
<% elsif @jibsa.j_option_06 == 815 %>
  <em>뉴트리웰</em>
<% elsif @jibsa.j_option_06 == 816 %>
  <em>퓨어비타</em>
<% elsif @jibsa.j_option_06 == 817 %>
  <em>한끼뚝딱</em>
<% elsif @jibsa.j_option_06 == 818 %>
  <em>세라피드</em>
<% elsif @jibsa.j_option_06 == 819 %>
  <em>뉴트리플랜</em>
<% elsif @jibsa.j_option_06 == 820 %>
  <em>사조동아원</em>
<% elsif @jibsa.j_option_06 == 821 %>
  <em>후새</em>
<% elsif @jibsa.j_option_06 == 822 %>
  <em>원더캐츠</em>
<% elsif @jibsa.j_option_06 == 823 %>
  <em>헤일로</em>
<% elsif @jibsa.j_option_06 == 824 %>
  <em>프리스키</em>
<% elsif @jibsa.j_option_06 == 825 %>
  <em>트로벳</em>
<% elsif @jibsa.j_option_06 == 826 %>
  <em>탐사</em>
<% elsif @jibsa.j_option_06 == 827 %>
  <em>위시본</em>
<% elsif @jibsa.j_option_06 == 828 %>
  <em>웰니스</em>
<% elsif @jibsa.j_option_06 == 829 %>
  <em>치킨수프 클래식</em>
<% elsif @jibsa.j_option_06 == 830 %>
  <em>슈슈</em>
<% elsif @jibsa.j_option_06 == 831 %>
  <em>올가밀 캣35</em>
<% elsif @jibsa.j_option_06 == 832 %>
  <em>마즈</em>
<% elsif @jibsa.j_option_06 == 833 %>
  <em>어스본홀리스틱</em>
<% elsif @jibsa.j_option_06 == 834 %>
  <em>이퀼리브리오</em>
<% elsif @jibsa.j_option_06 == 835 %>
  <em>뉴웨이브</em>
<% elsif @jibsa.j_option_06 == 836 %>
  <em>아카나</em>
<% elsif @jibsa.j_option_06 == 837 %>
  <em>풀무원</em>
<% elsif @jibsa.j_option_06 == 838 %>
  <em>풀무원 아미오</em>
<% elsif @jibsa.j_option_06 == 839 %>
  <em>밥이보약</em>
<% elsif @jibsa.j_option_06 == 840 %>
  <em>하림더리얼</em>
<% elsif @jibsa.j_option_06 == 841 %>
  <em>캣츠맘</em>
<% elsif @jibsa.j_option_06 == 842 %>
  <em>네츄럴랩</em>
<% end %>

app/views/jibsas/_codes_country.html.erb
<% if @jibsa.j_option_03 == 301 %>
  <span>한국</span>
<% elsif @jibsa.j_option_03 == 302 %>
  <span>미국</span>
<% elsif @jibsa.j_option_03 == 303 %>
  <span>캐나다</span>
<% elsif @jibsa.j_option_03 == 304 %>
  <span>독일</span>
<% end %>

app/views/jibsas/_codes_functional.html.erb
<% if @jibsa.j_spare_01.present? %>
  <p>면역력</p>
<% end %>
<% if @jibsa.j_spare_02.present? %>
  <p>헤어볼</p>
<% end %>
<% if @jibsa.j_spare_03.present? %>
  <p>체중조절</p>
<% end %>
<% if @jibsa.j_spare_04.present? %>
  <p>소화기능&변냄새</p>
<% end %>
<% if @jibsa.j_spare_05.present? %>
  <p>피부&모질 개선</p>
<% end %>
<% if @jibsa.j_spare_06.present? %>
  <p>뼈&관절 건강</p>
<% end %>
<% if @jibsa.j_spare_07.present? %>
  <p>치석&구강 건강</p>
<% end %>
<% if @jibsa.j_spare_08.present? %>
  <p>눈물&눈 건강</p>
<% end %>
<% if @jibsa.j_spare_09.present? %>
  <p>비뇨계</p>
<% end %>
<% if @jibsa.j_spare_10.present? %>
  <p>신장&심부전</p>
<% end %>

app/views/jibsas/_codes_ingredient.html.erb
<% if @jibsa.j_option_07 == 701 %>
  <span>소</span>
<% elsif @jibsa.j_option_07 == 702 %>
  <span>돼지</span>
<% elsif @jibsa.j_option_07 == 703 %>
  <span>닭</span>
<% elsif @jibsa.j_option_07 == 704 %>
  <span>오리</span>
<% elsif @jibsa.j_option_07 == 705 %>
  <span>양</span>
<% elsif @jibsa.j_option_07 == 706 %>
  <span>생선</span>
<% elsif @jibsa.j_option_07 == 707 %>
  <span>칠면조</span>
<% elsif @jibsa.j_option_07 == 708 %>
  <span>사슴</span>
<% elsif @jibsa.j_option_07 == 709 %>
  <span>탈수가금육</span>
<% elsif @jibsa.j_option_07 == 710 %>
  <span>곡물</span>
<% elsif @jibsa.j_option_07 == 711 %>
  <span>야채</span>
<% end %>

app/views/jibsas/_index_02.html.erb
<div class="index_box clearfix">
  <div class="index_left">  
    <div class="ctn_box">
      <h2>사랑하는 나의 반려묘<br />똑똑한 집사들을 위한 공간</h2>
      <p>건강한 반려모를 위한 사료 정보 제공을 위해 준비 중입니다.</p>
      <p>Coming Soon :)</p>
      <% if current_user && current_user.admin %>
        <a href="/jibsas">#블로그</a><br>
        <a href="/posts">#고양이 굿즈 스토어</a><br>
        <a href="/hubs/for_catfeed_store">#고양이 사료 스토어</a><br>
        <!-- <a href="/hubs/nutrition_dic">#고양이_영양소_백과사전</a> -->
      <% end %>
    </div>
  </div><!-- index_left -->

  
    <div class="index_right">
      <div class="index_wrap">

        <div class="ni_title">
          <h1><span>Food</span><p>Special For Your Cat</p></h1>
        </div>

        <div class="index_menu">
          <div class="find_food menu_box">
            <p><span></span>사료 성분</p>
            <div class="inner">
              <p>우리아이가 먹고있는 사료의<br/>영양 및 원료 성분을 알아보세요.</p>
              <a href="/hubs/for_catfeed_store">사료 성분분석 결과보기</a>
            </div>
          </div>

          <div class="match_food menu_box">
            <p><span></span>우리아이 맞춤 사료</p>
            <div class="inner">
              <p>우리아이에게 딱 맞는<br/>사료를 찾아보세요.</p>
              <a href="/hubs/for_catfeed_store">맞춤 사료 찾기</a>
            </div>
          </div>

          <div class="compare_food menu_box">
            <p><span></span>사료 비교</p>
            <div class="inner">
              <p>어떤 사료가 좋을지<br/>비교해보세요.</p>
              <a href="/hubs/product_comparison">사료 비교하기</a>
            </div>
          </div>
        </div>
        

        
      </div>
    </div><!-- end index_right -->
  

</div><!-- index_box -->

<%= javascript_pack_tag 'search_modal' %>

app/views/jibsas/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="form_box">
    <div class="wrap">
      <h1>Editing Jibsa</h1>
      <%= render 'form', jibsa: @jibsa %>
      <%= link_to 'Show', @jibsa %> |
      <%= link_to 'Back', jibsas_path %>
    </div>
  </div>
<% end %>

app/views/jibsas/hashtags.html.erb
<div class="index_box clearfix">
  <div class="index_left">  
    <div class="ctn_box">
      <h2>사랑하는 나의 반려묘<br />똑똑한 집사들을 위한 공간</h2>
      <p>건강한 반려모를 위한 &nbsp; 사료 정보를 제공합니다.</p>
      <% if current_user && current_user.admin %>
        <a href="/jibsas">#블로그</a><br>
        <a href="/posts">#고양이 굿즈 스토어</a><br>
        <a href="/hubs/for_cat_store">#고양이 용품 스토어</a><br>
      <% end %>
    </div>
  </div>

  <div class="index_right">
    <div class="index_wrap">
      <%= render '/posts/header' %>

      <section class="search search_pc">
        <div class="search-inner">
            <button class="search-button">
              <img src="<%=asset_path 'search.png'%>" alt="냥이굿즈 찾기">
            </button>
            <%= form_for "",url: jibsas_path, role: "search", method: :get do %>
              <%= text_field_tag :search, @search_term, placeholder: "사료 찾기", class: 'search-input' %>
            <% end %> 
          </div>
       </section>
      

      <%= render '/jibsas/navigation' %>
      <section class="title">
        <div class="hero">
          <img src="<%=asset_path 'hero_01.png'%>" alt="gift for cat lover" class="hero-image">
        </div>
        <div class="trending">
          <a href="/hubs/popular_today">#인기_많은_사료_TOP_10</a>
        </div>
        <h1>
          <% if current_user && current_user.admin %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => "navigation-item" %>
            <%= link_to '새로운 사료', new_jibsa_path, :class => "navigation-item" %>
            <%= link_to '새로운 블로그', new_feed_path, :class => "navigation-item" %>
          <% end %>
        </h1>
        
      </section>

      <%= render 'jibsas/index_section' %>
      
      <%= raw pagy_nav(@pagy) %>
      
    </div>

  </div><!-- end index_right -->
</div>

app/views/jibsas/new.html.erb
<% if current_user && current_user.admin %>
  <div class="form_box">
    <div class="wrap">
      <h1>New Jibsa</h1>
      <%= render 'form', jibsa: @jibsa %>
      <%= link_to 'Back', jibsas_path %>
    </div>
  </div>
<% end %>

app/views/jibsas/show.html.erb
<div class="index_box clearfix">
  <div class="index_left">  
    <div class="ctn_box">
      <h2>사랑하는 나의 반려묘<br />똑똑한 집사들을 위한 공간</h2>
      <p>건강한 반려모를 위한 사료 정보 제공을 위해 준비 중입니다.</p>
      <p>Coming Soon :)</p>
      <% if current_user && current_user.admin %>
        <a href="/jibsas">#블로그</a><br>
        <a href="/posts">#고양이 굿즈 스토어</a><br>
        <a href="/hubs/for_catfeed_store">#고양이 사료 스토어</a><br>
      <% end %>
    </div>
  </div>

  <% if current_user && current_user.admin %>
    <div class="index_right">
      
        <div class="index_wrap show_index">
          
          <%= render '/posts/header' %>
            
          <div class="show_card clearfix">

            <div class="image_box">
              <img src="<%= @jibsa.j_image %>" alt="<%= @jibsa.j_title %>" title="<%= @jibsa.j_title %>" />
            </div>
        
            <div class="inner_section">
              <div class="inner clearfix">
                
                <em><%= render 'jibsas/codes_brand' %>/ 
                  <p class="feeding_age"><% if @jibsa.j_option_02 == 201 %>
                      <span>키튼(1세 미만)</span>
                    <% elsif @jibsa.j_option_02 == 202 %>
                      <span>어덜트(1세 ~ 7세)</span>
                    <% elsif @jibsa.j_option_02 == 203 %>
                      <span>시니어(7세 이상)</span>
                    <% elsif @jibsa.j_option_02 == 204 %>
                      <span>전연령용</span>
                    <% end %>
                  </p>
                </em>                
                <h2><%= @jibsa.j_title %></h2>
                
                
                <p class="hashtag"><%= render_with_jhashtags(@jibsa.j_hashtag) %></p>
            

                <%= render 'jibsas/new_detail' %>
              </div>

              <div class="btn menu clearfix">
                <div class="menu-inner">
                  <button class="menu-item" onclick="goBack()">뒤로가기</button>
                  <!-- <a href="/" class="menu-item">뒤로가기</a> -->
                  <a target="_blank" href="<%= @jibsa.j_link %>" class="menu-item active">사러가기</a>
                   <div class="sale_cat">
                     <img src="<%=asset_path 'dont_go.png'%>" alt="세일알림이 냥이">
                   </div>
                </div>
                <script>
                  function goBack() {
                    window.history.back();
                  }
                </script>
              </div>
          </div><!-- inner -->
        
        </div><!-- show card -->
        <div class="notice clearfix">
          <ul>
            <li>가격과 평점이 다른가요? <a href="/hubs/about_us">[자세히 보기]</a></li>
            <% if @jibsa.j_source.present? %>
              <li>"JellyJellyJellyJelly"는 이 상품 판매의 당사자가 아닙니다.</li>
            <% else %>
              <li>"JellyJellyJellyJelly"는 이 상품 판매의 당사자가 아니며 쿠팡 파트너스 활동을 통해 일정의 수수료를 지급받아요.</li>
            <% end %>
            <% if current_user && current_user.admin %>
              <div class="admin_controller">
                <li><%= link_to 'Edit', edit_jibsa_path(@jibsa) %>| <%= link_to 'Destroy', @jibsa, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </div>
            <% end %>
          </ul>
        </div>
        <% if current_user && current_user.admin %>
            <%= render 'jibsas/filter' %>
            <% end %> 
        </div><!-- show_wrap -->

      <%= javascript_pack_tag 'search_modal' %>
    </div>
  <% end %>
  
</div>