config/routes.rb
Rails.application.routes.draw do
  
  resources :feeds
  resources :jibsas
  root 'posts#index'
  # root 'jibsas#index'
  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"
  
  devise_for :users
  resources :categories
  resources :posts
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/posts/hashtag/:name', to:'posts#hashtags'
  get '/jibsas/jhashtag/:name', to:'jibsas#hashtags'

  get '/404' , to: 'errors#not_found'
  get '/422' , to: 'errors#unacceptable'
  get '/500' , to: 'errors#server_errors'

  get 'hubs/seed_files'
  get 'hubs/about_us'
  get 'hubs/error_test'
  get 'hubs/popular'
  get 'hubs/random_view'
  get 'hubs/new_index'
  get 'hubs/popular_today'
  get 'hubs/dry_feed'
  get 'hubs/wet_feed'
  get 'hubs/nutrition_dic'
  get 'hubs/for_catfeed_store'
  get 'hubs/testing'
  get 'hubs/product_comparison'
  
  

  # Feed_detail
  get 'feed_detail/fd_01'
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController

  def seed_files
    @posts = Post.all.order("created_at DESC")
  end

  def popular
    @posts_day = Post.most_hit(1.day.ago, 10) 
    @posts_week = Post.most_hit(1.week.ago, 10) 
    @posts_month = Post.most_hit(1.month.ago, 10) 
  end

  def popular_today
    @posts_day = Post.most_hit(1.day.ago, 10) 
  end

  def random_view
    @posts_random = Post.offset(rand(Post.count)).limit(1)
  end

  def new_index
    @posts = Post.all.order("created_at DESC")
  end

  def for_catfeed_store
    @pagy, @jibsas = pagy(Jibsa.all.order("created_at DESC"), items: 20)
  end

  def testing
    @pagy, @jibsas = pagy(Jibsa.all.order("created_at DESC"), items: 20)
  end

  def product_comparison
    @jibsas = Jibsa.all.order("created_at DESC")
  end
end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/views/hubs/_popular_month.html.erb
<section class="title">
  <h1>Most Popular Cat Goods Top 10 in the last month</h1>
  <p>오늘 뷰가 가장 많은 굿즈 Top 10</p>
</section>

<section class="productlists clearfix">

  <% @posts_day.each_with_index do |post, i| %> 
    <div class="card_box">
      <div class="image_box">
        <%= link_to image_tag(post.image, alt: post.title, title: post.title), post %>
      </div>
      <div class="inner">
        
        <!--
        <% if post.source.present? %>
          <em>by <%= post.source %></em>
        <% else %>
          <em>by 쿠팡</em>
        <% end %>
        -->
        <% if current_user && current_user.admin %>
          <div class="admin_controller">
            <span><%= link_to 'Edit', edit_post_path(post) %></span>
            <span><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
            <span>Views: <%= post.hits %></span>
          </div>
        <% end %>
        <p class="p_title"><%= link_to post.title, post %></p>
        <% goods_pct = 0 %>
        <% goods_pct =  (post.was_price.to_f - post.is_price.to_f) / post.was_price.to_f * 100 %>
        <p class="p_price"><span><%= number_to_currency(post.is_price, locale: :kr) %>원</span></p>
        <% if post.was_price.present? %>
          <em class="was_price"><%= number_to_currency(post.was_price, locale: :kr) %>원</em>
          <em class="pct"> ( <%= number_to_percentage(goods_pct, precision: 0) %> off )</em>
        <% end %>
      </div>

      <% if post.was_price.present? %>
        <div class="sale_cat">
          <img src="<%=asset_path 'sale.png'%>" alt="세일알림이 냥이">
        </div>
      <% end %>

      <div class="numbering">
        <span><%= i + 1 %></span>
      </div>
    </div>
  <% end %>

</section>

app/views/hubs/_popular_week.html.erb
<section class="title">
  <h1>Most Popular Cat Goods Top 10 in the last week</h1>
  <p>한 주동안 뷰가 가장 많은 굿즈 Top 10</p>
</section>

<section class="productlists clearfix">

  <% @posts_week.each_with_index do |post, i| %> 
    <div class="card_box">
      <div class="image_box">
        <%= link_to image_tag(post.image, alt: post.title, title: post.title), post %>
      </div>
      <div class="inner">
        
        <!--
        <% if post.source.present? %>
          <em>by <%= post.source %></em>
        <% else %>
          <em>by 쿠팡</em>
        <% end %>
        -->
        <% if current_user && current_user.admin %>
          <div class="admin_controller">
            <span><%= link_to 'Edit', edit_post_path(post) %></span>
            <span><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
            <span>Views: <%= post.hits %></span>
          </div>
        <% end %>
        <p class="p_title"><%= link_to post.title, post %></p>
        <% goods_pct = 0 %>
        <% goods_pct =  (post.was_price.to_f - post.is_price.to_f) / post.was_price.to_f * 100 %>
        <p class="p_price"><span><%= number_to_currency(post.is_price, locale: :kr) %>원</span></p>
        <% if post.was_price.present? %>
          <em class="was_price"><%= number_to_currency(post.was_price, locale: :kr) %>원</em>
          <em class="pct"> ( <%= number_to_percentage(goods_pct, precision: 0) %> off )</em>
        <% end %>
      </div>

      <% if post.was_price.present? %>
        <div class="sale_cat">
          <img src="<%=asset_path 'sale.png'%>" alt="세일알림이 냥이">
        </div>
      <% end %>

      <div class="numbering">
        <span><%= i + 1 %></span>
      </div>
    </div>
  <% end %>

</section>

app/views/hubs/about_us.html.erb
<div class="wrap">
  <div class="index_wrap">
    <%= render '/posts/header' %>

    <div class="about_us">
      <div class="mission sections">
        <h2 class="headline">ABOUT US</h2>
        <div class="what_is">
          <div class="left">
            <p><span>#1</span>"JellyJellyJellyJelly"는 고양이를 테마로 하는 고양이 굿즈 큐레이팅 웹사이트 입니다. 다양한 냥이 굿즈를 국내 및 해외 사이트에서 큐레이팅하여 소개하고 있습니다. 고양이를 사랑하는 모든 분들을 위한 다양한 냥이굿즈 선물이 준비되어 있습니다.</p>
          </div>
          <div class="right">
            <p><span>#2</span> "JellyJellyJellyJelly"는 쿠팡, 알리익스프레스, 아마존을 비롯한 다양한 나라의 온라인 쇼핑몰과의 Affiliate Program을 통해 일정의 수수료를 지급 받고 받습니다. [It is a participant in the Amazon Services LLC Associates Program & the Amazon EU Associates Program.]</p>
          </div>
        </div>
        
      </div>


      <div class="qna sections clearfix">
       <p class="bodyline">Q & A</p>
       <h3># JellyJellyJellyJelly 어떤 Shop인가요?</h3>
       <p>"JellyJellyJellyJelly"는 국내 &해외에서 판매되고 있는 재밌고 귀여운 고양이 굿즈를 큐레이팅하는 큐레이션 웹사이트 입니다."<br />귀여운 고양이 굿즈를 어디에서 얼마에 살 수 있는지 간편하게 알아 볼 수있습니다.</p>
       <h3># 실제로 상품을 판매 하는건가요?</h3>
       <p>"JellyJellyJellyJelly"은 해당 상품을 판매하는 당사자가 아니며 큐레이팅한 상품의 판매자와 링크를 통해 판매 사이트로 연결을 해줍니다.</p>
       <h3># 상품의 페이지가 없거나 가격 정보가 다릅니다.</h3>
       <p>해당 상품의 포스팅 시간 기준으로 큐레이팅한 상품의 평점 및 리뷰 수 그리고 가격 정보가 달라질 수 있습니다. 또한 인기가 많은 상품의 경우 빠르게 품절이 될 수 있습니다.</p>
       
      </div>

      <div class="qna sections clearfix">
        <p class="bodyline">Source</p>
        <p>Copyright (c) 2022 by Håvard Brynjulfsen (https://codepen.io/havardob/pen/JjJXqZm) & Alex Bergin (https://codepen.io/abergin/pen/BaKVWd) & Adventures in Missions (https://codepen.io/adventuresinmissions/pen/ExwoWL) & by Brad Jackson (https://codepen.io/bssjackson/pen/OXXwWq) & by Mert Cukuren (https://codepen.io/knyttneve/pen/YeRVgL) & Chris (https://codepen.io/leetech/pen/wvzaNr) & by Darcy Voutt (https://codepen.io/darcyvoutt/pen/KKVWPW) & by Wanderson Jackson (https://codepen.io/Wandersonjack/pen/GVNbXL) & by Syahrizal (https://codepen.io/syrizaldev/pen/KKVeymK) & by Eric Porter (https://codepen.io/EricPorter/pen/NJgPba) & by Adam Henley (https://codepen.io/adamazing/pen/qaxeZG) & by Tony Montemorano (https://codepen.io/allusis/pen/EpKmwO) & by Alejandra Quetzalli (https://codepen.io/alejandra_quetzalli/pen/XjNaXy)






        Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

        The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p>

        <p><a href='https://www.freepik.com/vectors/cartoon'>Cartoon vector created by pch.vector - www.freepik.com</a></p>

      </div>


    </div>


  </div>
</div>

app/views/hubs/dry_feed.html.erb
<div class="index_box clearfix">
  <div class="index_left">  
    <div class="ctn_box">
      <h2>고양이 건식사료 <br />영양소 계산기</h2>
      <p>단백질, 탄수화물 지방 함량에 따른 하루 사료 권장량 계산하기</p>
      <a href="/hubs/wet_feed">#습식사료 계산하기</a>
    </div>
  </div>

  <% if current_user && current_user.admin %>
    <div class="index_right">
      <div class="index_wrap">
        <%= render '/posts/header' %>

        <section class="search search_pc">
          <div class="search-inner">
              <button class="search-button">
                <img src="<%=asset_path 'search.png'%>" alt="냥이굿즈 찾기">
              </button>
              <%= form_for "",url: feeds_path, role: "search", method: :get do %>
                <%= text_field_tag :search, @search_term, placeholder: "사료 정보 검색...", class: 'search-input' %>
              <% end %> 
            </div>
         </section>      
        
        <%= render '/jibsas/navigation' %>
        <br />


        <div id="outerbox" class="result_box clearfix">

          <ul class="feed_menu clearfix">
            <li><a class="active" href="/hubs/dry_feed">건식사료</a></li>
            <li><a href="/hubs/wet_feed">습식사료</a></li>
            <!-- <li><a href="#n">활동량</a></li>
            <li><a href="#n">사료량</a></li> -->
          </ul>
          

          <div id="box"> 
              <div class="label"><p class="formtext"> 조단백질</p> <input type="number" placeholder="0" class="form" id="protien"></div>
              <div class="label"><p class="formtext"> 조지방 </p> <input type="number" placeholder="0" class="form" id="fat"></div>
              <div class="label"><p class="formtext"> 칼슘 </p> <input type="number" placeholder="0" class="form" id="calcium"></div>
              <div class="label"><p class="formtext"> 인 </p> <input type="number" placeholder="0" class="form" id="phosphorus"></div>
              <div class="label"><p class="formtext"> 조섬유 </p> <input type="number" placeholder="0" class="form" id="fiber"></div>
              <div class="label"><p class="formtext"> 조회분 </p> <input type="number" placeholder="0" class="form" id="ash"></div>
              <div class="label"><p class="formtext"> 칼로리 </p> <input type="number" placeholder="0" class="form" id="calorie"></div>
              <div class="label"><p class="formtext"> 수분 </p> <input type="number" placeholder="0" class="form" id="water"></div>
              <p class="info_p">*칼로리를 모를 경우 4000을 입력해주세요.</p>
            <input type="submit" class="submit" onclick=nuTrient() diSplay() value="계산하기"></input>
          </div>
              
          <div class="ctn_result">
            <div class="without_water clearfix"> 
              <h4>*수분을 제외한 영양소 비율(DM)</h4>
              <!-- <p> 조단백: <span id="crudeProtein"></span>%</p> 
              <p> 조지방: <span id="fatContent"></span>%</p> 
              <p> 칼슘: <span id="calCium"></span>%</p> 
              <p> 인: <span id="phosPhorus"></span>%</p> -->    
              <table>
                <div class="highlight"></div>
                <tr>
                  <th colspan="3">AAFCO기준 일일 최소 영양성분 섭취량</th>
                  <!-- <br/>*4,000 kcal/kg, 수분 0%(DM, Dry Matter)기준 -->
                  <th></th>
                </tr>
                <tr>
                  <th>영양소</th>
                  <th>성장기 <br/>임신</th>
                  <th>성묘</th>
                  <th>DM</th>
                </tr>
                <tr>
                  <td>조단백질</td>
                  <td>30.0%</td>
                  <td>26.0%</td>
                  <td><span id="crudeProtein"></span>%</td>
                </tr>
                <tr>
                  <td>조지방</td>
                  <td>9.0%</td>
                  <td>9.0%</td>
                  <td><span id="fatContent"></span>%</td>
                </tr>
                <tr>
                  <td>칼슘</td>
                  <td>1.0%</td>
                  <td>0.6%</td>
                  <td><span id="calCium"></span>%</td>
                </tr>
                <tr>
                  <td>인</td>
                  <td>0.8%</td>
                  <td>0.5%</td>
                  <td><span id="phosPhorus"></span>%</td>
                </tr>
                <tr>
                  <td colspan="2">권장 탄수화물 함량<br/> <em>20% 이하<em></td>
                  <td colspan="2" class="nfe_in">탄수화물 함량<br/> <em><span id="blaNce"></span>%<em></td>
                </tr>
              </table>
            </div>

           <div class="info clearfix">
              <ul class="info_ul">
                <li>
                  <input type="checkbox" checked>
                  <i></i>
                  <h3>AAFCO란 무엇인가요?</h3>
                  <p>This page was written in HTML and CSS. The CSS was compiled from SASS. I used Normalize as my CSS reset and -prefix-free to save myself some headaches. I haven't quite gotten the hang of Slim for compiling into HTML, but someday I'll use it since its syntax compliments that of SASS. Regardless, this could all be done in plain HTML and CSS.</p>
                </li>
                <li>
                  <input type="checkbox" checked>
                  <i></i>
                  <h3>탄수화물 함량을 계산하는 이유?</h3>
                  <p>Using the sibling and checked selectors, we can determine the styling of sibling elements based on the checked state of the checkbox input element. One use, as demonstrated here, is an entirely CSS and HTML accordion element. Media queries are used to make the element responsive to different screen sizes.</p>
                </li>
                <li>
                  <input type="checkbox" checked>
                  <i></i>
                  <h3>수분을 제외하고 계산해야 하는 이유는?</h3>
                  <p>By making the open state default for when :checked isn't detected, we can make this system accessable for browsers that don't recognize :checked. The fallback is simply an open accordion. The accordion can be manipulated with Javascript (if needed) by changing the "checked" property of the input element.</p>
                </li>
              </ul>
            </div>

            
            <div class="calorie clearfix">
              <h4>*100g당 칼로리</h4>
              <div class="clearfix">
                <p>조단백질(kcal) <span id="protienKcal"></span></p> 
                <p>조지방(kcal)  <span id="fatKcal"></span></p> 
                <p>탄수화물(kcal) <span id="carboKcal"></span></p> 
              </div>
              <em>총 칼로리: <span class="total_ckal" id="totalKcal"></span><span class="total_ckal">kcal</span></em> 
            </div>

            <div class="blance clearfix">
              <h4>*100g당 탄단지(탄수화물, 단백질, 지방) 비율</h4>
              <p>조단백질(%) <span id="protienNutrient"></span></p> 
              <p>조지방(%) <span id="fatNutrient"></span></p> 
              <p>탄수화물(%) <span id="carboNutrient"></span></p> 
            </div>

            

            <!-- <p> 사료 라벨 조단백 <span id="justResult"></span>%</p>  -->
          </div>
      
        
      </div>
    </div><!-- end index_right -->
   <% end %> 
</div>
<%= javascript_pack_tag 'search_modal' %>



<script type="text/javascript">
// 고양이 사료 영양소 계산기 JS //
function nuTrient() {
  function find(id) {
    return document.getElementById(id);}
  var protien = find("protien").value;
  var calorie = find("calorie").value;
  var fat = find("fat").value;
  var phosphorus = find("phosphorus").value;
  var calcium = find("calcium").value;
  var water = find("water").value;
  var ash = find("ash").value;
  var fiber = find("fiber").value;


  //////// 사료 라벨 수치 ////////
  //조단백
  // var just_result = 0;
  //   just_result = protien;
  // find("justResult").innerHTML = just_result;

  //////// 수분을 제외한 영양소 비율 ////////
  //조단백
  var protien_result = 0;
    protien_result = 100 * protien / (100 - water)  * 4000 / calorie;
  // find("crudeProtein").innerHTML = Math.round(protien_result);
  find("crudeProtein").innerHTML = (protien_result.toFixed(1));

  //조지방
  var fat_result = 0;
    fat_result = 100 * fat / (100 - water)  * 4000 / calorie;
  // find("fatContent").innerHTML = Math.round(fat_result);
  find("fatContent").innerHTML = (fat_result.toFixed(1));

  //칼슘
  var calcium_result = 0;
    calcium_result = 100 * calcium / (100 - water)  * 4000 / calorie;
  find("calCium").innerHTML = (calcium_result.toFixed(1));

  //인
  var phosphorus_result = 0;
    phosphorus_result = 100 * phosphorus / (100 - water)  * 4000 / calorie;
  find("phosPhorus").innerHTML = (phosphorus_result.toFixed(1));

  //탄수화물 비율
  var carbo_blance_result = 0;
    carbo_blance_result = 100 - protien - fat - water - ash - fiber;
  find("blaNce").innerHTML = (carbo_blance_result.toFixed(1));


  //////// 100g 당 칼로리 ////////
  //100g 당 단백질 칼로리
  var protien_kcal_result = 0;
    protien_kcal_result = protien * 3.5;
  find("protienKcal").innerHTML = (protien_kcal_result.toFixed(1));    

  //100g 당 지방 칼로리
  var fat_kcal_result = 0;
    fat_kcal_result = fat * 8.5;
  find("fatKcal").innerHTML = (fat_kcal_result.toFixed(1));    

  //100g 당 탄수화물 칼로리
  var carbo_kcal_result = 0;
    carbo_kcal_result = carbo_blance_result * 3.5;
  find("carboKcal").innerHTML = (carbo_kcal_result.toFixed(1));    

  //100g 당 총 칼로리
  var total_kcal_result = 0;
    total_kcal_result = protien_kcal_result + fat_kcal_result + carbo_kcal_result;
  find("totalKcal").innerHTML = (total_kcal_result.toFixed(1));    

  //////// 100g 당 각 영양소(탄단지) 비율 ////////
  //100g 당 단백질 영양비율
  var protien_nutrient_result = 0;
    protien_nutrient_result = (protien_kcal_result / total_kcal_result) * 100;
  find("protienNutrient").innerHTML = (protien_nutrient_result.toFixed(1));    

  //100g 당 지방 영양비율
  var fat_nutrient_result = 0;
    fat_nutrient_result = (fat_kcal_result / total_kcal_result) * 100;
  find("fatNutrient").innerHTML = (fat_nutrient_result.toFixed(1));    

  //100g 당 탄수화물 영양비율
  var carbo_nutrient_result = 0;
    carbo_nutrient_result = (carbo_kcal_result / total_kcal_result) * 100;
  find("carboNutrient").innerHTML = (carbo_nutrient_result.toFixed(1));    

  }

</script>

app/views/hubs/new_index.html.erb
<div class="index_box clearfix">
  <div class="index_left">  
    <div class="ctn_box">
      <a href="#n">나는 집사입니다.</a>
    </div>
  </div>
  <div class="index_right">
    <div class="index_wrap">
      <%= render '/posts/header' %>
      <%= render '/posts/navigation' %>
      <section class="title">
        <div class="hero">
          <div class="hero-overlay">
            <!-- <h1>Bubbles</h1> -->
          </div>
          <img src="<%=asset_path 'hero_01.png'%>"" alt="gift for cat lover" class="hero-image">
        </div>
        <h1>
          <% if current_user && current_user.admin %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => "navigation-item" %>
            <%= link_to 'New Post', new_post_path, :class => "navigation-item" %>
            <%= link_to 'New Jibsa', new_jibsa_path, :class => "navigation-item" %>
          <% end %>
        </h1>
        
      </section>

      <%= render 'posts/index_section' %>

    </div>
  </div>
</div>

<%= javascript_pack_tag 'search_modal' %>

app/views/hubs/popular.html.erb
<div class="wrap">
  <div class="index_wrap">
    <%= render '/posts/header' %>
    <%= render '/posts/navigation' %>
    
    <!-- 오늘 뷰가 가장 많은 굿즈 -->
    <%= render '/hubs/popular_today' %>

    <!-- 한 주동안 뷰가 가장 많은 굿즈 -->
    <%= render '/hubs/popular_week' %>

    <!-- 한 달동안 뷰가 가장 많은 굿즈 -->
    <%= render '/hubs/popular_month' %>



  </div>
</div>

<%= javascript_pack_tag 'search_modal' %>

app/views/hubs/popular_today.html.erb
<div class="index_box clearfix">
  <div class="index_left">  
    <div class="ctn_box">
      <h2>고양이를 사랑하는<br />냥덕후들을 위한 공간</h2>
      <p>귀여운 고양이를 테마로 하는 굿즈를 큐레이팅 합니다.&nbsp;다양한 냥이 굿즈를 구경하세요.</p>
      <a href="/">#더_다양한_굿즈_구경가기</a>
    </div>
  </div>

  <div class="index_right">
    <div class="index_wrap">
      <%= render '/posts/header' %>

      <section class="search search_pc">
        <div class="search-inner">
            <button class="search-button">
              <img src="<%=asset_path 'search.png'%>" alt="냥이굿즈 찾기">
            </button>
            <%= form_for "",url: posts_path, role: "search", method: :get do %>
              <%= text_field_tag :search, @search_term, placeholder: "Search....", class: 'search-input' %>
            <% end %> 
          </div>
       </section>
      

      <%= render '/posts/navigation' %>

      <section class="title">
        <h2>오늘 하루 가장 인기 있는 냥이 굿즈 TOP10</h2>
      </section>

      <section class="productlists clearfix">

        <% @posts_day.each_with_index do |post, i| %> 
          <div class="card_box">
            <div class="image_box">
              <%= link_to image_tag(post.image, alt: post.title, title: post.title), post %>
            </div>
            <div class="inner">
              
              <!--
              <% if post.source.present? %>
                <em>by <%= post.source %></em>
              <% else %>
                <em>by 쿠팡</em>
              <% end %>
              -->
              <% if current_user && current_user.admin %>
                <div class="admin_controller">
                  <span><%= link_to 'Edit', edit_post_path(post) %></span>
                  <span><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
                  <span>Views: <%= post.hits %></span>
                </div>
              <% end %>
              <p class="p_title"><%= link_to post.title, post %></p>
              <% goods_pct = 0 %>
              <% goods_pct =  (post.was_price.to_f - post.is_price.to_f) / post.was_price.to_f * 100 %>
              <p class="p_price"><span><%= number_to_currency(post.is_price, locale: :kr) %>원</span></p>
              <% if post.was_price.present? %>
                <em class="was_price"><%= number_to_currency(post.was_price, locale: :kr) %>원</em>
                <em class="pct"> ( <%= number_to_percentage(goods_pct, precision: 0) %> off )</em>
              <% end %>
            </div>

            <% if post.was_price.present? %>
              <div class="sale_cat">
                <img src="<%=asset_path 'sale.png'%>" alt="세일알림이 냥이">
              </div>
            <% end %>

            <div class="numbering">
              <span><%= i + 1 %></span>
            </div>
          </div>
        <% end %>

      </section>
      
      

    </div>
  </div><!-- end index_right -->


</div>

<%= javascript_pack_tag 'search_modal' %>

app/views/hubs/seed_files.html.erb
<div class="wrap" style="padding:20px;">
  <% @posts.each do |post| %>
    <p style='margin:20px 0;'>#Post.create(
        user_id: 1, 

        <!-- 이미지 -->
        image: '<%= post.image %>', 

        <!-- 상품이름 -->
        title: '<%= post.title %>', 

        <!-- Friendly_Id -->
        spare_01: '<%= post.spare_01 %>', 

        <!-- 샹품 URL -->
        link: '<%= post.link %>', 

        <!-- 판매사이트 -->
        <% if post.source.present? %>
          source: '<%= post.source %>'
        <% else %>
          source: '쿠팡'
        <% end %>, 

        <!-- 해시태그 -->
        hashtag: '<%= post.hashtag %>', 

        <!-- 현재 가격 -->
        is_price: '<%= post.is_price %>', 

        <!-- 세일전 가격 -->
        <% if post.was_price.present? %>
          was_price: '<%= post.was_price %>'
        <% else %>
          was_price: ' '
        <% end %>, 

        <!-- 할인율 --><!-- 
        <% if post.was_price.present? %>
          <% goods_pct = 0 %>
          <% goods_pct =  (post.was_price.to_f - post.is_price.to_f) / post.was_price.to_f * 100 %>
          pct: '<%= goods_pct %>'
        <% else %>
          pct: ' '
        <% end %>, -->
        
        <!-- 별점 --> 
        <% if post.spare_56.present? %>
          spare_56: '<%= post.spare_56 %>'
        <% else %>
          spare_56: ' '
        <% end %> )
      </p>



  <% end %>
</div>